#!/bin/bash
set -e

"$(dirname "$(readlink -f "$BASH_SOURCE")")/git-set-file-times"

IFS=$'\n'
topLevelDirs=( $(find -mindepth 1 -maxdepth 1 -type d -not -name .git) )
unset IFS

IFS=$'\n'
allDirs=( $(find "${topLevelDirs[@]}" -depth -type d) . )
unset IFS

for dir in "${allDirs[@]}"; do
	ref="$(ls -At "$dir" | grep -v '^.git$' | head -1)"
	if [ "$ref" ]; then
		touch --reference "$dir/$ref" "$dir"
	fi
done
