#!/bin/bash
set -e

IFS=$'\n'
files=( $(git ls-files) )
unset IFS

for f in "${files[@]}"; do
	stamp="$(git --no-pager log -1 --format='format:%ci' -- "$f")"
	touchFormat="$(date --date="$stamp" +'%Y%m%d%H%M.%S')"
	touch --no-dereference -t "$touchFormat" "$f"
done
